name: CI

on:
  push:
    branches: [ main, ci/self-hosted-gpu-runner ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-15, ubuntu-24.04-arm, ubuntu-24.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Lint
      run: |
        scripts/lint.sh

  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-15]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Test
      run: |
        scripts/test.sh

  test-gpu:
    runs-on: [self-hosted, macOS, ARM64]
    permissions:
      contents: read
    env:
      HF_HOME: ${{ runner.temp }}/hf_cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: GPU smoke test
      run: |
        scripts/test.sh

    - name: GPU model tests (slow)
      run: |
        scripts/test-gpu.sh
